# search in google as nginx conf in configmap --> stack overflow
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx
  namespace: expense
data:
  nginx.conf: | # (| is very important)  
    user nginx;
    worker_processes auto; # for indentation use tab button from here
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    # Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
    include /usr/share/nginx/modules/*.conf;

    events {
        worker_connections 1024;
    }

    http {
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile            on;
        tcp_nopush          on;
        tcp_nodelay         on;
        keepalive_timeout   65;
        types_hash_max_size 2048;

        include             /etc/nginx/mime.types;
        default_type        application/octet-stream;

        # Load modular configuration files from the /etc/nginx/conf.d directory.
        # See http://nginx.org/en/docs/ngx_core_module.html#include
        # for more information.
        include /etc/nginx/conf.d/*.conf;

        server {
            #listen       80 default_server; #for docker container
            #listen       [::]:80 default_server;  #for docker container
            listen       8080 default_server; #for pod container
            listen       [::]:8080 default_server; #for pod container
            server_name  _;
            root         /usr/share/nginx/html;

            # Load configuration files for the default server block.
            include /etc/nginx/default.d/*.conf;

          location  /api/ {
        	proxy_pass http://backend:8080/;  #proxy_pass http://localhost:8080/; when we use host network
    	    }
    	
            error_page 404 /404.html;
                location = /40x.html {
            }

            error_page 500 502 503 504 /50x.html;
                location = /50x.html {
            }
        }
    }
    
         
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  # labels of deployment resource
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      # It won't refer the nginxconfig from image,it refer the nginxconfig from configmap 
      # we added config as volume
      volumes: 
      - name: nginx
        configMap:
          name: nginx
          items:
          - key: nginx.conf
            path: nginx.conf
      containers:
      - name: nginx
        image: poojarivinod1/frontend:1.2.0
        resources: # This is copied from 07-resources.yaml
        # soft limit (minimum)
          requests:
            memory: "68Mi"
            cpu: "100m"
        # hard limit (maximum)
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports: # when you free check without this ports
        - containerPort: 8080
        # volume is mount on the /etc/nginx/nginx.conf path
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true     
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector: # labels are used as selectors, it connects to that pod
    app: frontend
    tier: web
    project: expense
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 8080 # target container port
---
# search in google as hpa in kubernetes --> HorizontalPodAutoscaler Walkthrough
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5 #for testing # if cpu increase more than 5% then create replicas